modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="random_mod"
version="1.0.0"
displayName="Random Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jomst, MCreator"

[[dependencies.random_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




